/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.angwyn.gradle.`cp-1`

//class App {
//    val greeting: String
//        get() {
//            return "Hello world."
//        }
//}
//
//fun main(args: Array<String>) {
//    println(App().greeting)
//}

fun isPrime(x: Int, i: Int = 2): String {
    if (x <= 2) {
        return if (x == 2) "is a prime number" else "is not a prime number"
    }
    if (x % i == 0) return "is not a prime number"
    if (i * i > x) return "is a prime number"
    return isPrime(x, i + 1)
}

fun main(){
    println(isPrime(3))
    println(isPrime(4))
    println(isPrime(7))
}